"""dccrn_model.py — Experiment 3 TinyDCCRN architecture (deployment-only copy).

This file is the SOLE SOURCE OF TRUTH for the neural-network architecture when
running inference, pruning, quantization, or benchmarking.

Architecture extracted verbatim from train_dccrn_3.py (Experiment 3).
Do NOT edit this file independently — any change to the model architecture
must first be made in train_dccrn_3.py and then propagated here.

Experiment 3 enhancement formulation
-------------------------------------
    raw_output  = TinyDCCRN(noisy_stft_input)          # [B, 2, F, T]
    M_r = tanh(raw_output[:, 0] / mask_bound) * mask_bound
    M_i = tanh(raw_output[:, 1] / mask_bound) * mask_bound
    enh_r = (1 + M_r) * noisy_r  -  M_i * noisy_i
    enh_i = (1 + M_r) * noisy_i  +  M_i * noisy_r
    S_enhanced = complex(enh_r, enh_i)

Default hyperparameters (must match the training Config)
---------------------------------------------------------
    model_channels   : (16, 32, 64)
    gru_hidden_size  : 128
    gru_layers       : 1
    n_fft            : 512
    hop_length       : 128
    win_length       : 512
    sample_rate      : 16000
    mask_bound       : 2.0
"""
from __future__ import annotations

from typing import List, Sequence, Tuple

import torch
import torch.nn as nn
from torch import Tensor


# ---------------------------------------------------------------------------
# Default hyperparameters (kept in sync with train_dccrn_3.py Config)
# ---------------------------------------------------------------------------

DEFAULT_CHANNELS: Tuple[int, ...] = (16, 32, 64)
DEFAULT_GRU_HIDDEN: int = 128
DEFAULT_GRU_LAYERS: int = 1
DEFAULT_N_FFT: int = 512
DEFAULT_HOP_LENGTH: int = 128
DEFAULT_WIN_LENGTH: int = 512
DEFAULT_SAMPLE_RATE: int = 16_000
DEFAULT_MASK_BOUND: float = 2.0
# Segment used during training → determines STFT frame count used to probe
# the encoder during construction.
DEFAULT_SEGMENT_SAMPLES: int = DEFAULT_SAMPLE_RATE * 2  # 2 s = 32 000 samples


# ---------------------------------------------------------------------------
# Complex convolution building blocks
# ---------------------------------------------------------------------------

class ComplexConv2d(nn.Module):
    """Complex-valued convolution using paired real/imag real-valued Conv2d layers.

    Input/output channel convention: paired channels, real at even indices,
    imag at odd indices.  Stride is applied identically to both real and imag
    paths.  Kernel size is fixed at 3×3, padding=1 to preserve spatial dims
    before striding.
    """

    def __init__(self, in_channels: int, out_channels: int, stride: Tuple[int, int]):
        super().__init__()
        self.real = nn.Conv2d(in_channels, out_channels, 3, stride, 1)
        self.imag = nn.Conv2d(in_channels, out_channels, 3, stride, 1)

    def forward(self, x: Tensor) -> Tensor:
        real, imag = x[:, 0::2], x[:, 1::2]
        return torch.stack(
            (self.real(real) - self.imag(imag), self.real(imag) + self.imag(real)), dim=2
        ).flatten(1, 2)


class ComplexConvTranspose2d(nn.Module):
    """Complex-valued transposed convolution (decoder / upsampling path)."""

    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        stride: Tuple[int, int],
        output_padding: Tuple[int, int],
    ):
        super().__init__()
        self.real = nn.ConvTranspose2d(
            in_channels, out_channels, 3, stride, 1, output_padding=output_padding
        )
        self.imag = nn.ConvTranspose2d(
            in_channels, out_channels, 3, stride, 1, output_padding=output_padding
        )

    def forward(self, x: Tensor) -> Tensor:
        real, imag = x[:, 0::2], x[:, 1::2]
        return torch.stack(
            (self.real(real) - self.imag(imag), self.real(imag) + self.imag(real)), dim=2
        ).flatten(1, 2)


# ---------------------------------------------------------------------------
# TinyDCCRN
# ---------------------------------------------------------------------------

class TinyDCCRN(nn.Module):
    """Lightweight GRU-based DCCRN variant operating on paired complex channels.

    Input shape : [B, 2, F, T]  — real/imag stacked along channel dim
    Output shape: [B, 2, F, T]  — raw mask logits (NOT the enhanced spectrum)

    The CRM application (apply_crm) must be performed AFTER the forward pass
    to convert the raw output into an enhanced spectrogram.  This separation
    is preserved here so that the state_dict matches the training checkpoint
    exactly.
    """

    def __init__(
        self,
        channels: Sequence[int],
        gru_hidden: int,
        gru_layers: int,
        input_shape: Tuple[int, int],
    ):
        super().__init__()
        if len(channels) != 3:
            raise ValueError("TinyDCCRN requires exactly three model channel stages")
        self.channels = tuple(channels)

        # --- Encoder ---------------------------------------------------------
        enc: List[nn.Module] = []
        in_channels = 1
        strides = [(2, 2), (2, 2), (1, 2)]
        for index, out_channels in enumerate(channels):
            enc += [
                ComplexConv2d(in_channels, out_channels, strides[index]),
                nn.BatchNorm2d(out_channels * 2),
                nn.PReLU(),
            ]
            in_channels = out_channels
        self.encoder = nn.ModuleList(enc)

        # Probe encoder to determine GRU input size (same method as training).
        with torch.no_grad():
            encoded = torch.zeros(1, 2, *input_shape)
            for layer in self.encoder:
                encoded = layer(encoded)
        _, encoded_channels, encoded_frequency, _ = encoded.shape
        self.gru_input_size = encoded_channels * encoded_frequency

        # --- GRU bottleneck --------------------------------------------------
        self.gru = nn.GRU(self.gru_input_size, gru_hidden, gru_layers, batch_first=True)
        self.gru_projection = nn.Linear(gru_hidden, self.gru_input_size)

        # --- Decoder ---------------------------------------------------------
        dec: List[nn.Module] = []
        reversed_channels = list(reversed(channels))
        decoder_strides = [(1, 2), (2, 2), (2, 2)]
        decoder_output_padding = [(0, 0), (0, 1), (0, 0)]
        for i, current in enumerate(reversed_channels):
            out_channels = reversed_channels[i + 1] if i + 1 < len(reversed_channels) else 1
            dec += [
                ComplexConvTranspose2d(
                    current, out_channels, decoder_strides[i], decoder_output_padding[i]
                )
            ]
            if i + 1 < len(reversed_channels):
                dec += [nn.BatchNorm2d(out_channels * 2), nn.PReLU()]
        self.decoder = nn.ModuleList(dec)

    def forward(self, x: Tensor) -> Tensor:
        """Forward pass: noisy complex spectrogram → raw CRM logits.

        Args:
            x: [B, 2, F, T] float32 tensor with real and imaginary parts.

        Returns:
            y: [B, 2, F, T] raw mask logits — pass to apply_crm() to get the
               enhanced spectrogram.
        """
        if x.ndim != 4 or x.shape[1] != 2:
            raise ValueError(f"Expected [B, 2, F, T] complex input, got {tuple(x.shape)}")
        skips: List[Tensor] = []
        y = x
        for layer in self.encoder:
            y = layer(y)
            if isinstance(layer, ComplexConv2d):
                skips.append(y)

        b, c, f, t = y.shape
        sequence = y.permute(0, 3, 1, 2).reshape(b, t, c * f)
        sequence, _ = self.gru(sequence)
        y = self.gru_projection(sequence).reshape(b, t, c, f).permute(0, 2, 3, 1)

        decoder_index = 0
        skip_indices = (1, 0)   # first decoder stage ← encoder stage 1, second ← stage 0
        for layer in self.decoder:
            y = layer(y)
            if isinstance(layer, ComplexConvTranspose2d) and skips:
                if decoder_index < len(skip_indices):
                    skip = skips[skip_indices[decoder_index]]
                    if y.shape != skip.shape:
                        diff_f = skip.shape[-2] - y.shape[-2]
                        diff_t = skip.shape[-1] - y.shape[-1]
                        y = torch.nn.functional.pad(y, (0, diff_t, 0, diff_f))
                    y = y + skip
                decoder_index += 1

        if y.shape != x.shape:
            diff_f = x.shape[-2] - y.shape[-2]
            diff_t = x.shape[-1] - y.shape[-1]
            y = torch.nn.functional.pad(y, (0, diff_t, 0, diff_f))
        return y


# ---------------------------------------------------------------------------
# CRM application (must be called after TinyDCCRN.forward)
# ---------------------------------------------------------------------------

def apply_crm(
    model_output: Tensor,
    noisy_spec: Tensor,
    mask_bound: float = DEFAULT_MASK_BOUND,
) -> Tuple[Tensor, Tensor]:
    """Apply a bounded Complex Ratio Mask (CRM) to the noisy spectrogram.

    Experiment 3 enhancement formulation (verbatim from train_dccrn_3.py):
        M_r = tanh(output_r / mask_bound) * mask_bound
        M_i = tanh(output_i / mask_bound) * mask_bound
        enh_r = (1 + M_r) * noisy_r  -  M_i * noisy_i
        enh_i = (1 + M_r) * noisy_i  +  M_i * noisy_r

    At zero initialisation:
        M = 0  →  S_enh = S_noisy   (exact identity)

    Args:
        model_output : [B, 2, F, T]  raw logits from TinyDCCRN.forward()
        noisy_spec   : [B, F, T]     complex STFT of the noisy input
        mask_bound   : tanh saturation value (default 2.0)

    Returns:
        enhanced_spec : [B, F, T]  complex tensor — ready for iSTFT
        mask          : [B, F, T]  complex mask M — for statistics / debugging
    """
    mask_r = torch.tanh(model_output[:, 0] / mask_bound) * mask_bound
    mask_i = torch.tanh(model_output[:, 1] / mask_bound) * mask_bound

    noisy_r = noisy_spec.real
    noisy_i = noisy_spec.imag

    enh_r = (1.0 + mask_r) * noisy_r - mask_i * noisy_i
    enh_i = (1.0 + mask_r) * noisy_i + mask_i * noisy_r

    return torch.complex(enh_r, enh_i), torch.complex(mask_r, mask_i)


# ---------------------------------------------------------------------------
# Model factory
# ---------------------------------------------------------------------------

def build_model(
    channels: Tuple[int, ...] = DEFAULT_CHANNELS,
    gru_hidden: int = DEFAULT_GRU_HIDDEN,
    gru_layers: int = DEFAULT_GRU_LAYERS,
    n_fft: int = DEFAULT_N_FFT,
    hop_length: int = DEFAULT_HOP_LENGTH,
    win_length: int = DEFAULT_WIN_LENGTH,
    sample_rate: int = DEFAULT_SAMPLE_RATE,
    segment_samples: int = DEFAULT_SEGMENT_SAMPLES,
    device: torch.device = torch.device("cpu"),
) -> TinyDCCRN:
    """Construct a TinyDCCRN with the correct STFT-derived input_shape.

    This mirrors build_model() in train_dccrn_3.py.  The STFT probe step
    determines (F, T) from the n_fft and segment_samples so the GRU
    input_size is computed identically to training.
    """
    # Compute STFT output shape using a zero waveform (no audio needed).
    window = torch.hann_window(win_length)
    probe = torch.zeros(1, segment_samples)
    spec = torch.stft(
        probe, n_fft, hop_length, win_length, window,
        return_complex=True, center=True,
    )
    input_shape = (spec.shape[-2], spec.shape[-1])   # (F, T)
    model = TinyDCCRN(channels, gru_hidden, gru_layers, input_shape).to(device)
    return model


def load_checkpoint(
    checkpoint_path: str,
    device: torch.device = torch.device("cpu"),
    strict: bool = True,
) -> Tuple[TinyDCCRN, dict]:
    """Load an Experiment 3 checkpoint produced by train_dccrn_3.py.

    The checkpoint dict contains:
        model_state_dict        : OrderedDict — weights
        model_config            : {channels, gru_hidden_size, gru_layers}
        stft_config             : {sample_rate, n_fft, hop_length, win_length}
        epoch                   : int
        validation_loss         : float
        best_validation_loss    : float
        config                  : full training Config as dict
        optimizer_state_dict    : (ignored at inference)
        scheduler_state_dict    : (ignored at inference)

    Args:
        checkpoint_path : path to .pth file
        device          : target device
        strict          : if True, raise on missing/unexpected keys

    Returns:
        model     : TinyDCCRN with weights loaded, in eval() mode
        meta      : the full checkpoint dict (epoch, loss, configs, …)
    """
    ckpt = torch.load(checkpoint_path, map_location=device, weights_only=False)

    mc = ckpt.get("model_config", {})
    sc = ckpt.get("stft_config", {})

    channels    = tuple(mc.get("channels", DEFAULT_CHANNELS))
    gru_hidden  = int(mc.get("gru_hidden_size", DEFAULT_GRU_HIDDEN))
    gru_layers  = int(mc.get("gru_layers", DEFAULT_GRU_LAYERS))
    n_fft       = int(sc.get("n_fft", DEFAULT_N_FFT))
    hop_length  = int(sc.get("hop_length", DEFAULT_HOP_LENGTH))
    win_length  = int(sc.get("win_length", DEFAULT_WIN_LENGTH))
    sample_rate = int(sc.get("sample_rate", DEFAULT_SAMPLE_RATE))

    # segment_samples is derived from the full config if available
    full_cfg    = ckpt.get("config", {})
    seg_sec     = float(full_cfg.get("segment_seconds", 2.0))
    segment_samples = int(sample_rate * seg_sec)

    model = build_model(
        channels=channels,
        gru_hidden=gru_hidden,
        gru_layers=gru_layers,
        n_fft=n_fft,
        hop_length=hop_length,
        win_length=win_length,
        sample_rate=sample_rate,
        segment_samples=segment_samples,
        device=device,
    )

    missing, unexpected = model.load_state_dict(ckpt["model_state_dict"], strict=strict)
    model.eval()

    return model, ckpt


def load_quantized_model(
    quantized_checkpoint_path: str,
    base_checkpoint_path: str = "C:/SIH/Experiment_03_Identity_Residual/checkpoints/Experiment_03_best.pth",
    device: torch.device = torch.device("cpu"),
) -> Tuple[nn.Module, dict]:
    """Load a dynamic INT8 quantized TinyDCCRN model checkpoint.

    Reconstructs the model architecture, applies dynamic quantization structure,
    and loads the quantized state_dict.
    """
    try:
        import torch.ao.quantization as quantization
    except ImportError:
        import torch.quantization as quantization

    base_model, meta = load_checkpoint(base_checkpoint_path, device=device)
    base_model.eval()

    q_model = quantization.quantize_dynamic(
        base_model,
        qconfig_spec={nn.GRU, nn.Linear},
        dtype=torch.qint8
    )

    ckpt = torch.load(quantized_checkpoint_path, map_location=device, weights_only=False)
    state = ckpt.get("model_state_dict", ckpt)
    q_model.load_state_dict(state)
    q_model.eval()

    return q_model, meta

